### ISSUE TITLE
Set up Homebrew and Scoop installation, update README

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/cumulus#139]
https://github.com/ubclaunchpad/scoop-bucket
https://github.com/ubclaunchpad/homebrew-tap

Awesome project, no easy way of trying it out 😢 Would be cool to have some distribution channels set up, and update the README with a project description, images, and links to further reading (the wiki + Medium post)

I could set this up too, need write permissions to the repo tho 👍

**Comment by bobheadxi** [comment]
I could set up dep as well while I'm at it

**Comment by jordanschalm** [comment]
You should have write access now @bobheadxi

**Comment by bobheadxi** [comment]
Thanks Jordan!
