### ISSUE TITLE
Miner PoW Prototype

### ISSUE THREAD

**Issue by chadlagore** [ubclaunchpad/cumulus#40]
## Miner PoW Prototype

🥈 Create a Prototype for miner's proof of work.

### Additional Information

🏃 Miners compete to solve a `Puzzle` (which is produced with the hash of the most recent `Block` appended to the `Blockchain`).
🔫 For a prototype, we want Miners to repeatedly hash their own `Wallet` concatenated with some random string of bits.
😶 The first Miner who generates a hash that is similar enough to the `Puzzle` hash has "mined" the next block.

**Comment by jordanschalm** [comment]
@david-julien Can you add an estimate to this when you get to it?

**Comment by jordanschalm** [comment]
@david-julien let's not close issues until they're merged 😛
